/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projet.tache.ihm;

import java.awt.CardLayout;
import java.util.ArrayList;
import projet.tache.command.undoredo.Command;
import projet.tache.mvc.Model;



/**
 *
 * @author 21204707
 */
public class FenetreTache extends javax.swing.JFrame {
private PanelTache PanelTache;
private PanelAfficher PanelAfficher;
private Model model;

    /**
     * Creates new form FenetreTache
     */
    public FenetreTache() {
        
        initComponents();
        setTitle("Gestion des tâches");
        PanelTache = new PanelTache();
        PanelAfficher = new PanelAfficher();
        getContentPane().add(PanelTache, "EditTache");
        getContentPane().add(PanelAfficher, "AffTache");
        pack();

        CardLayout c= (CardLayout)getContentPane().getLayout();
        c.show(this.getContentPane(), "EditTache");        
        
        
        setModel(new Model());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BtnTS = new javax.swing.JRadioButtonMenuItem();
        BtnTC = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jMenu1.setText("Gérer Tâches");

        BtnTS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup1.add(BtnTS);
        BtnTS.setSelected(true);
        BtnTS.setText("EditTâche");
        BtnTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTSActionPerformed(evt);
            }
        });
        jMenu1.add(BtnTS);

        BtnTC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup1.add(BtnTC);
        BtnTC.setText("AfficherTâche");
        BtnTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTCActionPerformed(evt);
            }
        });
        jMenu1.add(BtnTC);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Undo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Redo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
        PanelTache.setModel(model);
        PanelAfficher.setModel(model);
    }
    private void BtnTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTSActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "EditTache");
    }//GEN-LAST:event_BtnTSActionPerformed

    private void BtnTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTCActionPerformed
        // TODO add your handling code here:
         CardLayout cl = (CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "AffTache");
    }//GEN-LAST:event_BtnTCActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       // try{
        Command c = redoCommands.remove(redoCommands.size()-1);
        c.execute();
        PanelTache.commands.add(c);
        PanelTache.inicbx();
       // }catch(Exception e){
            
       // }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    private ArrayList<Command> redoCommands = new ArrayList<>();
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //try{
        Command c = PanelTache.commands.remove(PanelTache.commands.size()-1);
        c.undo();
        redoCommands.add(c);
        PanelTache.inicbx();
        //}catch(Exception e){
            
        //}
    }//GEN-LAST:event_jMenuItem1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreTache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreTache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreTache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreTache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreTache().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem BtnTC;
    private javax.swing.JRadioButtonMenuItem BtnTS;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
